### ISSUE TITLE
[AWS-S3] : aws-s3 file uploading is not happening

### ISSUE THREAD

**Issue by roopan-sellanyhome** [yii2-starter-kit/yii2-file-kit#110]
![screenshot from 2017-04-19 07 52 45](https://cloud.githubusercontent.com/assets/25365954/25160739/7a1e09a8-24d5-11e7-855b-d0a0b6bb598b.png)

**Comment by fbalabanov** [comment]
I have resolved it.
please, look at the Storage.php

origin source :

    public function save($file, $preserveFileName = false, $overwrite = false, $config = [])
    {
        $fileObj = File::create($file);
        $dirIndex = $this->getDirIndex();
        if ($preserveFileName === false) {
            do {
                $filename = implode('.', [
                    Yii::$app->security->generateRandomString(),
                    $fileObj->getExtension()
                ]);
                $path = $this->targetDir . implode('/', [$dirIndex, $filename]);
            } while ($this->getFilesystem()->has($path));
        } else {
            $filename = $fileObj->getPathInfo('filename');
            $path = $this->targetDir . implode('/', [$dirIndex, $filename]);
        }

        $this->beforeSave($fileObj->getPath(), $this->getFilesystem());

        **$stream = fopen($fileObj->getPath(), 'rb+');**

        $config = array_merge(['ContentType' => $fileObj->getMimeType()], $config);
        if ($overwrite) {
            $success = $this->getFilesystem()->putStream($path, $stream, $config);
        } else {
            $success = $this->getFilesystem()->writeStream($path, $stream, $config);
        }

		if (is_resource($stream)) {
			fclose($stream);
		}

        if ($success) {
            $this->afterSave($path, $this->getFilesystem());
            return $path;
        }

        return false;
    }

this function should be following like :
    public function save($file, $preserveFileName = false, $overwrite = false, $config = [])
    {
        $fileObj = File::create($file);
        $dirIndex = $this->getDirIndex();
        if ($preserveFileName === false) {
            do {
                $filename = implode('.', [
                    Yii::$app->security->generateRandomString(),
                    $fileObj->getExtension()
                ]);
                $path = $this->targetDir . implode('/', [$dirIndex, $filename]);
            } while ($this->getFilesystem()->has($path));
        } else {
            $filename = $fileObj->getPathInfo('filename');
            $path = $this->targetDir . implode('/', [$dirIndex, $filename]);
        }

        $this->beforeSave($fileObj->getPath(), $this->getFilesystem());

        **$stream = fopen($fileObj->getPath(), 'r+');**

        $config = array_merge(['ContentType' => $fileObj->getMimeType()], $config);
        if ($overwrite) {
            $success = $this->getFilesystem()->putStream($path, $stream, $config);
        } else {
            $success = $this->getFilesystem()->writeStream($path, $stream, $config);
        }

		if (is_resource($stream)) {
			fclose($stream);
		}

        if ($success) {
            $this->afterSave($path, $this->getFilesystem());
            return $path;
        }

        return false;
    }

**Comment by fbalabanov** [comment]
https://github.com/fbalabanov/yii2-file-kit.git

**Comment by bitmatix** [comment]
Same problem here. @fbalabanov changing Storage.php to:

`$stream = fopen($fileObj->getPath(), 'r+');`

doesn't help.
