### ISSUE TITLE
delete url == null when we updating saved model.

### ISSUE THREAD

**Issue by forzac** [yii2-starter-kit/yii2-file-kit#117]
If i add some images to the model and save it to db. Then when we open(load) this model to update and would like to delete image, there is no delete url and therefore no Ajax request to delete image. file.delete_url returns nothing. When we just create new model and add new images without saving to db it works fine and return us url but when we've saved data to db and open to update file.delete_url is empty.

**upload-kit.js**
```
            createItem: function(file){
                var name = options.name;
                var index = methods.getNumberOfFiles();
                if (options.multiple) {
                    name += '[' + index + ']';
                }
               
                var item = $('<li>', {"class": "upload-kit-item done"})
       .append($('<span/>', {"class": "glyphicon glyphicon-remove-circle remove", "data-url": file.delete_url}));
```

I've fixed it with adding:
```
var deleteUrl = '/some_controller_to_delete_image_action/image-delete?path=' + file.path.replace("/", "%2F");

 var item = $('<li>', {"class": "upload-kit-item done"})
                    .append($('<span/>', {"class": "glyphicon glyphicon-remove-circle remove", "data-url": deleteUrl}));

```
With this changes works fine when we load saved model.

**Comment by XzAeRo** [comment]
You must pass the delete_url parameter manually, this is not done automatically.
