### ISSUE TITLE
loading more than 2 files

### ISSUE THREAD

**Issue by crocone** [yii2-starter-kit/yii2-file-kit#146]
Uploading three files. I only pass 2 at the output image[0] and image[1]
```
<?= \trntv\filekit\widget\Upload::widget([
        'name' => 'image',
        'hiddenInputId' => 'filename',
        'maxNumberOfFiles' => 5,  
        'acceptFileTypes' => new \yii\web\JsExpression('/(\.|\/)(jpe?g|png)$/i'), 
]); ?>
```

![o9cfn8dacs](https://user-images.githubusercontent.com/43406446/51799217-01791d80-2230-11e9-87e6-05f88facd284.png)

**Comment by TheElk** [comment]
Still the same problem!!! I've solved this problem by replacing:
**"yii2-starter-kit/yii2-file-kit": "*",**
to
**"trntv/yii2-file-kit": "^1.0.0",**
in composer.phar

But i think that's not good idea.

![20190205235542](https://user-images.githubusercontent.com/14090191/52305674-c650ba00-29a6-11e9-81ba-ae07b2201ab3.png)

**Comment by nikosid** [comment]
I don't understand. In your code you have already fixed this issue but it doesn't update by composer.

**Comment by TheElk** [comment]
> I don't understand. In your code you have already fixed this issue but it doesn't update by composer.

This is a tempolary solution by me. 
I've changed code in composer.json and updated all definitions. 
Problem has solved.

But i think, problem must be solved at current module level by author or contributors.

**Comment by TheElk** [comment]
**nikosid**, please open your issue _Problem with upload widget #667_ again to to attract the attention of the module Creator. Thank you.

**Comment by XzAeRo** [comment]
Please, feel free to create a PR so I can merge this fix as soon as possible.

**Comment by TheElk** [comment]
I would love to, but unfortunately, not strong in Javascript and at the moment I can not help with the code of this module. I don't know why it works with "trntv/yii2-file-kit", because the repository is renamed. 

Maybe it will be enough just to take JS files from it and place in "trntv/yii2-file-kit"?

**Comment by rivieiraa** [comment]
@XzAeRo i guess you just neet to push forward package version on github. Version installed wih yii2-starter-kit and actual master branch source code on github are not equal.

Source on github:
https://github.com/yii2-starter-kit/yii2-file-kit/blob/4d16854411c42f27c65a64d5ceda48729dccc0c0/src/widget/assets/js/upload-kit.js#L202-L208

Installed via composer:
```
getNewItemIndex: function () {
    var existingIndexes = []
    $container.find('.files .upload-kit-item').each(function () {
         existingIndexes.push($(this).val());
    })
    return existingIndexes.length ? (Math.max(...existingIndexes)+1) : 0;
},
```

**Comment by XzAeRo** [comment]
Thank you @rivieiraa ! That was it! I was going mad over this, and couldn't figure out the issue, but this was it!

Also, the minified file wasn't generated, so running the software without debug mode, would use "the old version".

It should be fixed now! Thanks everyone for your time :)
