### ISSUE TITLE
Maybe somebody can write this widget by vueJs?

### ISSUE THREAD

**Issue by awebc** [yii2-starter-kit/yii2-file-kit#158]
you can?

**Comment by XzAeRo** [comment]
What do you mean? The underlying widget, made by [blueimp](https://github.com/blueimp/jQuery-File-Upload), is explicitly built for jQuery, so trying to make this widget work with Vue might be really tedious. Not to mention this widget has been built to be integrated with yii2, which is heavily reliant on bootstrap/jQuery dependencies for its widget rendering.
