### ISSUE TITLE
Combining and Compressing Assets

### ISSUE THREAD

**Issue by Clyff** [yii2-starter-kit/yii2-file-kit#85]
I followed the tutorial of  [Combining and Compressing Assets](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#combining-compressing-assets) in my project and i found a problem while compressing the `trntv\filekit\widget\UploadAsset`.

The compressed file is generated fine and my asset.php file shows me that the asset is empty like the others:

```
...
'trntv\\filekit\\widget\\UploadAsset' => [
    'sourcePath' => null,
    'js' => [],
    'css' => [],
    'depends' => [
        'yii\\web\\JqueryAsset',
        'yii\\bootstrap\\BootstrapAsset',
        'trntv\\filekit\\widget\\BlueimpFileuploadAsset',
        'all',
    ],
],
...
```

But when i look in my `app/web/assets` folder, the original files are still being generated and my debug shows this:
![debug](https://cloud.githubusercontent.com/assets/7630386/15788110/29794a60-299c-11e6-82cb-33cd4e8acd73.jpg)

My problem is the `init()`method of that class. If I remove the original `init()` and set the properties directly, like this:

``` php
    class UploadAsset extends AssetBundle
    {
        public $sourcePath = __DIR__ . "/assets";

        public $css = [
            YII_DEBUG ? 'css/upload-kit.css' : 'css/upload-kit.min.css'
        ];

        public $js = [
            YII_DEBUG ? 'js/upload-kit.js' : 'js/upload-kit.min.js'
        ];

        public $depends = [
            'yii\web\JqueryAsset',
            'yii\bootstrap\BootstrapAsset',
            'trntv\filekit\widget\BlueimpFileuploadAsset'
        ];
    }
```

The application will work fine. Is there any reason to use this method instead of setting the properties?

**Comment by Insolita** [comment]
https://github.com/trntv/yii2-file-kit/blob/master/src/widget/UploadAsset.php#L21
If you set settings ini init() method, it make impossible to overwrite bundle with AssetManager config
