### ISSUE TITLE
fclose(): 191 is not a valid stream resource

### ISSUE THREAD

**Issue by miroslav-chandler** [yii2-starter-kit/yii2-file-kit#90]
Привет! :)
Загружаю файл через UploadAction.
Файл адаптер - creocoder\flysystem\AwsS3Filesystem

Файл загружается на S3, но с ошибкой:
Проблема:
В файле vendor/trntv/yii2-file-kit/src/Storage.php:117, открывается файл с помощью функции fopen() - она возвращает ресурс.
После закачки файла на амазон, через $this->getFilesystem()->writeStream(), файл закрывается функцией fclose($stream), но Guzzle, уже закрыл ресурс в деструкторе.
vendor/guzzle/guzzle/src/Guzzle/Stream/Stream.php:77

```
    public function close()
    {
        if (is_resource($this->stream)) {
            fclose($this->stream);
        }
        $this->cache[self::IS_READABLE] = false;
        $this->cache[self::IS_WRITABLE] = false;
    }
```

Инициализировав его ранее в fromString в vendor/guzzle/guzzle/src/Guzzle/Http/EntityBody.php:76

```
    public static function fromString($string)
    {
        $stream = fopen('php://temp', 'r+');
        if ($string !== '') {
            fwrite($stream, $string);
            rewind($stream);
        }

        return new static($stream);
    }
```

**Comment by trntv** [comment]
``is_resource()`` же вернет ``false`` закрытому ресурсу. Наш ``fclose`` вообще не должен вызыватся тогда.
