### ISSUE TITLE
how to remove base_url field?

### ISSUE THREAD

**Issue by hellosimple** [yii2-starter-kit/yii2-file-kit#94]
I dont want to use two fields to save a image.
Single image in article use thumbnail_base_url and thumbnail_path.
Multi images in article_attachment use base_url and path.
file_storage_item use base_url and path.

My question is how to remove thumbnail_base_url and base_url, and only use one path field.
I have tried much but failed. Please help.
Thank you.

**Comment by xiaomalover** [comment]
You can extends the upload behavior like bellow.
`<?php

namespace shop\components;

use Yii;
use trntv\filekit\behaviors\UploadBehavior as BaseUploadBehavior;
use yii\helpers\ArrayHelper;

class UploadBehavior extends BaseUploadBehavior
{

    /**
     * Overwrite the parent Behavior to ignore the base_url attribute.
     * @return void
     */
    public function afterFindSingle()
    {
        $file = array_map(function ($attribute) {
            return $this->owner->getAttribute($attribute);
        }, $this->fields());

        if ($file['base_url'] == false) {
            $file['base_url'] = Yii::$app->fileStorage->baseUrl;
        }

        if (array_key_exists('path', $file) && $file['path']) {
            $this->owner->{$this->attribute} = $this->enrichFileData($file);
        }
    }

    /**
     * Overwrite the parent Behavior to ignore the base_url attribute.
     * @return void
     */
    public function afterFindMultiple()
    {
        $models = $this->owner->{$this->uploadRelation};
        $fields = $this->fields();
        $data = [];
        foreach ($models as $k => $model) {
            /* @var $model \yii\db\BaseActiveRecord */
            $file = [];
            foreach ($fields as $dataField => $modelAttribute) {
                $file[$dataField] = $model->hasAttribute($modelAttribute)
                    ? ArrayHelper::getValue($model, $modelAttribute)
                    : null;
            }
            if ($file['path']) {
                $data[$k] = $this->enrichFileData($file);
            }

            if ($data[$k]['base_url'] == false) {
                $data[$k]['base_url'] = Yii::$app->fileStorage->baseUrl;
            }
        }
        $this->owner->{$this->attribute} = $data;
    }
}
`

and then the the model like bellow

`public function behaviors()
    {
        return [
            [
                'class' => UploadBehavior::className(),
                'attribute' => 'images_input',
                'multiple' => true,
                'uploadRelation' => 'goodsImages',
                'pathAttribute' => 'image_url',
                'baseUrlAttribute' => false,
                'orderAttribute' => 'order',
                'typeAttribute' => 'type',
                'sizeAttribute' => 'size',
                'nameAttribute' => 'name',
            ],
            [
                'class' => UploadBehavior::className(),
                'attribute' => 'original_img_input',
                'pathAttribute' => 'original_img',
            ]
        ];
    }`
