### ISSUE TITLE
Saving file with 'preserveFileName=true'

### ISSUE THREAD

**Issue by robotE13** [yii2-starter-kit/yii2-file-kit#95]
When saving a file with preserving the original name the extension is truncated.

This is because the method `File::getPathInfo($part)` with `$part='filename'` returns the name without the extension, at `Storage::save():114`. Perhaps need use param `$path='basename'`?

**Comment by zvinger** [comment]
I have the same issue too. It would be perfect to have possibility to define full upload path with filename and extension.
